version: '3'

services:
  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "8090:8090"
    volumes:
      - ./www:/var/www:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./snippets:/etc/nginx/snippets:ro
      - ./protect:/etc/nginx/protect:ro
    networks:
      - glassfish-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    depends_on:
      - nginx-proxy
    volumes:
      - ./ssl:/etc/letsencrypt
      - ./ssl-log:/var/log/letsencrypt
      - ./www/.well-known:/var/www/.well-known
    profiles:
      - certbot
    command: [
      "renew",
    ]
    networks:
      - glassfish-network

  glassfish:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: glassfish
    ports:
      - "4848:4848"
      - "8080:8080"
    networks:
      - glassfish-network

networks:
  glassfish-network:
    external: true
